Month 7/step 2
lexanikitin/react-burger pull request #2
Opened 2022-12-30 12:51 UTC by lexanikitin

2022-12-31 07:35 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
1. В компоненте BurgerConstructor не хватает типизации одного пропса.
2. В консоли есть несколько ошибок.
<img width="557" alt="Снимок экрана 2022-12-31 в 10 33 24" src="https://user-images.githubusercontent.com/60173362/210129161-0ecc67df-49ec-49ef-88c9-261111b69031.png">

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Сделали отписку от слушателя событий
- Добавили проверку успешности запроса
- Записываете ошибку запроса в стейт

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-12-31 07:35 UTC, andryxxa93 commented on src/components/app/App.jsx
> +  const getIngredientsFromApi = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-12-31 07:35 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +BurgerConstructor.propTypes = {
**Необходимо исправить**
Не все пропсы типизированы

2022-12-31 07:35 UTC, andryxxa93 commented on src/components/modal-overlay/ModalOverlay.jsx
> +const ModalOverlay = ({isActive, setter, children}) => {
**Можно лучше**
у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2022-12-31 07:35 UTC, andryxxa93 commented on src/utils/order.js
> +const order = [
**Можно лучше**
Файл уже можно удалить

2023-01-01 09:49 UTC, lexanikitin commented on src/utils/order.js
> +const order = [
для проверки корректности отображения состава заказа пока оставил этот файл с данными

2023-01-01 10:26 UTC, lexanikitin commented on src/components/burger-constructor/BurgerConstructor.jsx
> +BurgerConstructor.propTypes = {
Done

2023-01-01 10:38 UTC, lexanikitin commented on src/components/app/App.jsx
> +  const getIngredientsFromApi = async () => {
Done

2023-01-01 11:08 UTC, lexanikitin commented on src/components/modal-overlay/ModalOverlay.jsx
> +const ModalOverlay = ({isActive, setter, children}) => {
Суть понял, сейчас получилось объединение функции компонента подложки и контейнера. Нехорошее решение. Разделю при дальнейшем развитии проекта в след спринте.

2023-01-02 11:31 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-02-04 12:49 UTC, merged