Month 9/step 1
lexanikitin/react-burger pull request #5
Opened 2023-03-14 10:58 UTC by lexanikitin

Готов к первой итерации ревью

2023-03-14 11:37 UTC, andryxxa93 requested changes
Что понравилось в работе:
- Есть механизм обновления токена
- Есть защита роутов для авторизованных и не авторизованных юзеров
- Роутинг настроен и работает корректно.

Что необходимо исправить:
- Лого принято делать ссылкой на главную страницу
- accessToken лучше хранить в куках - дело в том, что сейчас если авторизоваться и обновить страницу, то сначала валится запрос на получение данных юзера, потом срабатывает обновление токена, а только потом всё-таки получаем данные юзера. Т.е. 3 запроса выходит, хотя если хранить accessToken не в хранилище, которое стирается, а в куках, то можно сразу получать данные юзера, без дополнительных запросов.

<img width="1439" alt="Снимок экрана 2023-03-14 в 14 09 59" src="https://user-images.githubusercontent.com/60173362/224983373-6dc2dd72-fee5-4f4a-9131-e1851ad20e86.png">

- После успешного прохождения запроса на регистрацию необходимо редиректить на главную страницу. Не то юзеру будет непонятно - получилось зарегистрироваться или нет.

<img width="1417" alt="Снимок экрана 2023-03-14 в 14 10 49" src="https://user-images.githubusercontent.com/60173362/224983580-dba145d8-fe56-4e77-97d9-c04fb79d24fb.png">

- Если ввести в форму сброса пароля неверный код восстановления, то всё равно перебрасывает на главную - стоит дожидаться ответа сервера. Лучше всего будет показывать юзеру сообщение об ошибке, но это не обязательно.
<img width="1440" alt="Снимок экрана 2023-03-14 в 14 12 25" src="https://user-images.githubusercontent.com/60173362/224983958-d00e4ddc-e0fe-4e23-925f-4ac538a401fd.png">

 - В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".


**Можно лучше**
- Не нужно записывать в localStorage ни выбранную булку, ни выбранный ингредиент. В `localStorage` обычно записываются какие-то простые данные, например токены. Работа с localStorage довольно дорогостоящая для системы.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-14 11:37 UTC, andryxxa93 commented on src/components/app/App.jsx
> +          <Route path='/profile' element={<OnlyAuthRouteElement element={<Profile/>}/>}>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-14 11:37 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
>    var total = useMemo(() => {
**Можно лучше**
`var` уже не стоит использовать, это старый синтаксис и у `var` несколько другое поведение в отличие от `let` и `const`.

2023-03-14 11:37 UTC, andryxxa93 commented on src/pages/login/Login.jsx
> +  useEffect(()=>{if(loginIsSuccess){navigate('/')}},[loginIsSuccess]);
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-03-14 11:37 UTC, andryxxa93 commented on src/pages/reset-password/ResetPassword.jsx
> +  useEffect(()=>{
**Можно лучше**
Для большей читаемости добавьте пустые строки между смысловыми блоками программы

2023-03-14 12:38 UTC, lexanikitin commented on src/components/app/App.jsx
> +          <Route path='/profile' element={<OnlyAuthRouteElement element={<Profile/>}/>}>
На будущее учту.

2023-03-14 12:40 UTC, lexanikitin commented on src/components/burger-constructor/BurgerConstructor.jsx
>    var total = useMemo(() => {
Исправил

2023-03-14 12:44 UTC, lexanikitin commented on src/pages/login/Login.jsx
> +  useEffect(()=>{if(loginIsSuccess){navigate('/')}},[loginIsSuccess]);
Исправил. Это было дублирование функционала, маршрут защищен

2023-03-14 12:46 UTC, lexanikitin commented on src/pages/reset-password/ResetPassword.jsx
> +  useEffect(()=>{
Готово

2023-03-14 12:53 UTC, lexanikitin commented
Комментарии к обязательным правкам: 
1. Лого стало ссылкой на главную. 
2. accessToken переехал в куки, лишний запрос больше не вызывается
3. Редирект при успешной регистрации сделан. 
4. форма сброса пароля - скорректирована работа с событием успешности запроса
5. Панель навигации адаптивна и в шапке и в профиле. Есть непонимание к какому маршруту отнести страницы логин, регистрация, смены пароля. В данный момент шапка на эти страницы не реагирует, в задании нет пояснения.

По вопросу отображения сообщений для пользователя. Понимаю, что они нужны (в идеале), для них сделаны все флаги. Однако это достаточно большой объем работы и, если он не обязателен, то я его осознанно пропускаю.

2023-03-15 05:33 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-20 13:41 UTC, closed without merging