Month 9/step 2
lexanikitin/react-burger pull request #6
Opened 2023-03-20 13:42 UTC by lexanikitin

Готов к первому ревью!

2023-03-20 14:57 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
**Что понравилось**:
- Сделали раздельное хранение данных полученных по сокету для авторизованного и не авторизованного юзера.
- Сделали отдельные экшены для приватных и публичных данных полученных по сокету.
- Хорошо разобрались с сокетами.

- При открытии конкретного заказа из "Ленты заказов" происходит ошибка. То же происходит и с "Историей заказов".

<img width="1440" alt="Снимок экрана 2023-03-20 в 17 39 49" src="https://user-images.githubusercontent.com/60173362/226374060-678d0d86-c361-48ee-807f-f2afedf6ede8.png">

- В карточке заказа происходит не совсем корректный подсчет булок. Если посмотреть на карточку выходит, что в заказе 3 булки, хотя от сервера пришло конечно же 2.

<img width="1440" alt="Снимок экрана 2023-03-20 в 17 44 36" src="https://user-images.githubusercontent.com/60173362/226375537-f2d98d87-3399-430f-904c-badb8f202405.png">

- Так же необходимо повторяющиеся ингредиенты в заказе суммировать. Так же как с булками.

- Сокеты необходимо закрывать сокет соединение сразу же при уходе со страниц "История заказов" и "Лента заказов". Сейчас судя по экшенам оно не закрывается.

- У вас при открытии конкретного заказа в адресную строку добавляется символ точки с запятой перед айди заказа - он там не нужен.

<img width="628" alt="Снимок экрана 2023-03-20 в 17 49 35" src="https://user-images.githubusercontent.com/60173362/226377013-3a66ef00-4542-4d17-b659-a16c534ef33d.png">

- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Пожалуйста, посоветуйтесь с наставником.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-20 14:57 UTC, andryxxa93 commented on src/services/middleware/socketMiddleware.js
> +        socket.onmessage = event => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-03-21 14:27 UTC, lexanikitin commented
Добрый день ! Комментарии к моим исправлениям:

1. Ошибки при открытии заказов и их reload - отловил. На тестах больше не обнаружил.
2. Подсчет булок сбоит из-за полного отсутствия в задании прошлого спринта формата для отправки заказа на сервер. В моем случае прошел формат одна булка первая в списке и дальше ингредиенты в нужной последовательности. Знаю что другие студенты сделали варианты с булками по обоим концам заказа (с точки зрения логики - лишнее, т.к. разные булки не допустимы , следовательно это лишняя строка просто ) , так же среди заказов встречал только булки и 3 булки . Т.е. отправляют все кто что хочет , верификации на сервере нет. Поэтому сделал отображение и подсчет исходя из моего формата отправки данных.
3. Суммирование ингредиентов. С точки зрения бизнес логики у нас имеет значение последовательность ингредиентов в бургере, это часть кастомизации заказа. Последовательность ингредиентов берется из конструктора,  отправляется на сервер, затем получается и отображается в лентах заказов. Если мы считаем последовательность важной, то ее важно донести до конца цепочки , а не выкинуть по пути. Клиент выбрал , и должен увидеть свой выбор в личном кабинете. Сгруппировать не сложно , если настаиваете , то сделаю. Но по мне это противоречит логике. 
4.  Сокеты теперь закрываются. 
5. наличие двоеточия пришло из прошлого спринта у меня, не вспомню почему так сделал, видимо в каком-то скриншоте задания увидел или чтото. Самому не нравится, но исправлять по чуть чуть в достаточно многих местах. Если подтверждаете , то исправляю. 
6. Механизм роутинга из примера изучил. Нам не давался ранее. Используется TS , которого еще не было. Поэтому еще в прошлом спринте сделал свой с флагами и стейтами и прочим. Громоздко, требует большого рефакторинга, но работает.

2023-03-22 08:22 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-23 10:51 UTC, merged